### ISSUE TITLE
Reimplement Community Tree Browser Aspect

### ISSUE THREAD

**Issue by wwtamu** [TAMULib/dspace-angular#14]
https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/config/xmlui.xconf#L88

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/resources/aspects/CommunityTreeBrowser/sitemap.xmap

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/java/org/tdl/dspace/communityview/CommunityTreeBrowser.java

Add `tamu` theme shared component for collapsing sub communities and collections at the community collection views.

***This shared component and community/collection views overridden to use it will require use of the shared component in theme-based overrides of the same community/collection views.***

This component should include expand all and collapse all buttons.

To looks like

![Image](https://github.com/TAMULib/dspace-angular/assets/144841721/059d86c2-5fa4-45e2-91b6-99d9b01cb7ac)

If possible, list children community/collection as tree and exclude the self community/collection as root of the tree.

Use component for collection and community browsing: https://labs.library.tamu.edu/dspace7/community-list

![Image](https://github.com/TAMULib/dspace-angular/assets/144841721/3ead43fa-45cf-4c4b-bd64-f897dae7ffbd)

**Comment by jsavell** [comment]
Links to 6x implementation:
https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/java/org/tdl/dspace/communityview/CommunityTreeBrowser.java
https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/resources/aspects/CommunityTreeBrowser/sitemap.xmap
https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/scripts/community-list.js

**Comment by wwtamu** [comment]
@jcreel has provided additional requirements for this issue to address the limitations of asynchronously expanding subcommunities and collections. He proposed that the expand button expand the entire level of whichever has not been expanded. This, however, complicates the logic of simply expanding the nodes that are expandable. Which means a state will be required in the component or store indicating which level has been expanded as to not expand nested levels that have been expanded manually with the carrot icon button of the tree.
