### ISSUE TITLE
Reimplement Capstones theme

### ISSUE THREAD

**Issue by jsavell** [TAMULib/dspace-angular#3]
https://oaktrust.library.tamu.edu/handle/1969.1/94972
https://oaktrust.library.tamu.edu/handle/1969.1/94973

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/config/xmlui.xconf#L187

https://github.com/TAMULib/DSpace/tree/tamu-dspace-6.3/dspace/modules/xmlui/src/main/webapp/themes/Mirage2Ext/Capstones

**Comment by jsavell** [comment]
The 6x version of the Capstones theme does not include a link for the Client/sponsor field: https://oaktrust.library.tamu.edu/handle/1969.1/188695

For acceptance, the 7x version of the theme needs to have the anchor tag removed, preferably by utilizing a different, existing dspace angular provided component.

**Comment by wwtamu** [comment]
`dc.contributor.sponsor` falls under `ValueListBrowseDefinition` within `dc.contributor.*` causing the generic item page field to render as a browser definition link.
