### ISSUE TITLE
[DSpace 7 Upgrade] Add Google Tag Manager

### ISSUE THREAD

**Issue by wwelling** [TAMULib/dspace-angular#31]
Spreadsheet w/ the google tags available. (Bonnie has it)
(https://drive.google.com/drive/folders/1PSXJcEQEgOZcVL0_ZN7EsuTiyzMzVHXh)

Inserted using entrypoint and set using an env variable in the production deployment.

**Comment by Dbreck-TAMU** [comment]
Spreadsheet w/ the google tags available. (Bonnie has it)

Inserted using entrypoint and set using an env variable in the production deployment.

**Comment by qtamu** [comment]
There is a Google analytics configuration, for Google tags, built in. We may only need to create an environment variable for the actual tag and uncomment the line. 
https://github.com/TAMULib/DSpace/blob/9381bcc575ccb5528c802b9033f1bfde160e818a/dspace/config/dspace.cfg#L1504

**Comment by wwtamu** [comment]
https://wiki.lyrasis.org/display/DSDOC7x/Search+Engine+Optimization

**Comment by wwtamu** [comment]
Confirm with @bonniegardner and @jcreel whether we want to utilize DSpace 7 server-side Google analytics and add Google tag manager scripting to the index.html in dspace-angular.

Options:
- template index.html in tl_docker dspace-angular deployment
- attempt customizing dspace-angular within themes and custom source locations
- modify dspace-angular index.html and applicable components outside of themes

**Comment by wwtamu** [comment]
Note that if choosing to implement a custom dspace-angular component to incorporate google analytics tag manager we will not be able to provide analytics for browsing with JavaScript disabled and would have additional complexity to enable Google Analytics for bitstream download links.

https://support.google.com/analytics/answer/6165470?hl=en

I recommend we just configure following https://wiki.lyrasis.org/display/DSDOC7x/DSpace+Google+Analytics+Statistics.

**Comment by qtamu** [comment]
Bonnie was able to provide us with a test script and tag [here](https://drive.google.com/drive/folders/1IyifQFkP_TDTL70qR0G0Fju7_0mntFpZ)

**Comment by wwelling** [comment]
Do we want to track bitstream downloads using Solr and/or GA4?
