### ISSUE TITLE
[DSpace 7 Upgrade] Reimplement proxy license steps for submission workflow customizations

### ISSUE THREAD

**Issue by wwelling** [TAMULib/dspace-angular#49]
~Blocks https://github.com/TAMULib/DSpace/issues/202~

Missing TAMU Customizations or entire file customization:

edu.tamu.dspace.proxylicense.ProxyLicenseStep
edu.tamu.dspace.proxylicense.XmluiProxyLicenseStep

May need to be transferred to DSpace repository or another issue be created in DSpace repository.

**Comment by Dbreck-TAMU** [comment]
Start w/ bringing files over and see how they interact w/ the codebase. Cocoon pipeline is no longer available.

**Comment by wwtamu** [comment]
Here are the TAMU custom proxy license steps:

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/java/edu/tamu/dspace/proxylicense/ProxyLicenseStep.java
https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/modules/xmlui/src/main/java/edu/tamu/dspace/proxylicense/XmluiProxyLicenseStep.java

**Comment by wwelling** [comment]
DSpace issue for the server-side component of this step, https://github.com/TAMULib/DSpace/issues/229.
